d5_11_practice/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('p_library.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

p_library/urls.py
# Url диспетчер приложения p_library
from django.urls import path
from p_library.views import (
    BookListView, BookDetailView, BookCreateView, BookUpdateView, BookDeleteView, 
    AuthorCreateView, AuthorUpdateView, AuthorDeleteView,
    FriendCreateView, FriendUpdateView, FriendDeleteView,
)

app_name = 'p_library'

AuthorURLConf=[
    path('author/add', AuthorCreateView.as_view(), name='author_add'),
    path('author/<int:author_id>/edit', AuthorUpdateView.as_view(), name='author_edit'),
    path('author/<int:author_id>/delete', AuthorDeleteView.as_view(), name='author_delete'),
]
BookURLConf=[
    path('<int:author_id>', BookListView.as_view(), name='books_list'),
    path('book/<int:book_id>', BookDetailView.as_view(), name='book_detail'),
    path('book/<int:author_id>/add', BookCreateView.as_view(), name='book_add'),
    path('book/<int:book_id>/update', BookUpdateView.as_view(), name='book_update'),
    path('book/<int:book_id>/delete',BookDeleteView.as_view(), name='book_delete'),
]
FriendURLConf=[
    path('book/<int:author_id>/friend/add',FriendCreateView.as_view(), name='friend_add'),
    path('book/friend/<int:friend_id>/edit',FriendUpdateView.as_view(), name='friend_edit'),
    path('book/friend/<int:friend_id>/delete',FriendDeleteView.as_view(), name='friend_delete'),
]

urlpatterns = AuthorURLConf + BookURLConf + FriendURLConf

templates/includes/modals/author_modal_add.html
<!-- Модальное окно для добавления автора -->
<div class="modal fade" id="AuthorAddModal" tabindex="-1" role="dialog" aria-labelledby="AuthorAddModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="AuthorAddModalLabel">Добавить автора</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form method="POST" action="{% url 'p_library:author_add' %}">
            <div class="form-group">
              <label for="recipient-name" class="col-form-label">Полное имя автора: </label>
              <input type="text" class="form-control" id="recipient-name" placeholder="Гоголь Николай Васильевич" name="full_name"required>
            </div>
            <div class="form-group">
              <label for="message-text" class="col-form-label">Дата рождения: </label>
              <input type="text" class="form-control" id="message-text" placeholder="1809" name="birth_year" required></textarea>
            </div>
            <div class="form-group">
              <label for="message-text" class="col-form-label">Страна: </label>
              <input type="text" class="form-control" id="message-text" placeholder="RU" name="country" required></input>
            </div>
            <input type="submit" class="btn btn-success" value="Добавить"></button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть окно</button>
          </form>
        </div>
      </div>
    </div>
  </div>

templates/includes/modals/author_modal_edit.html
{% load crispy_forms_tags %}
<!-- Модальное окно для редактирования данных автора -->
<div class="modal fade" id="AuthorEditModal" tabindex="-1" role="dialog" aria-labelledby="AuthorEditModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="AuthorEditModalLabel">Редиктировать данные автора</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form  method="POST" action="{% url 'p_library:author_edit' author_id=author_by.id %}">
  
            <div class="form-group">
              {{author_form.full_name|as_crispy_field}}
            </div>
            <div class="form-group">
              {{author_form.birth_year|as_crispy_field}}
            </div>
            <div class="form-group">
    
              {{author_form.country|as_crispy_field}}
            </div>
            <input type="submit" class="btn btn-info" value="Сохранить"></button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть окно</button>
          </form>
          <form action="{% url 'p_library:author_delete' author_id=author_by.id %}" method="POST">
              <input type="submit" class="btn btn-danger mt-2" value="Удалить"></button>
          </form>
          
        </div>
      </div>
    </div>
  </div>
  