d5_11_practice/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('p_library.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

p_library/urls.py
# Url диспетчер приложения p_library
from django.urls import path
from p_library.views import (
    BookListView, BookDetailView, BookCreateView, BookUpdateView, BookDeleteView, 
    AuthorCreateView, AuthorUpdateView, AuthorDeleteView,
    FriendCreateView, FriendUpdateView, FriendDeleteView,
)

app_name = 'p_library'

AuthorURLConf=[
    path('author/add', AuthorCreateView.as_view(), name='author_add'),
    path('author/<int:author_id>/edit', AuthorUpdateView.as_view(), name='author_edit'),
    path('author/<int:author_id>/delete', AuthorDeleteView.as_view(), name='author_delete'),
]
BookURLConf=[
    path('<int:author_id>', BookListView.as_view(), name='books_list'),
    path('book/<int:book_id>', BookDetailView.as_view(), name='book_detail'),
    path('book/<int:author_id>/add', BookCreateView.as_view(), name='book_add'),
    path('book/<int:book_id>/update', BookUpdateView.as_view(), name='book_update'),
    path('book/<int:book_id>/delete',BookDeleteView.as_view(), name='book_delete'),
]
FriendURLConf=[
    path('book/<int:author_id>/friend/add',FriendCreateView.as_view(), name='friend_add'),
    path('book/friend/<int:friend_id>/edit',FriendUpdateView.as_view(), name='friend_edit'),
    path('book/friend/<int:friend_id>/delete',FriendDeleteView.as_view(), name='friend_delete'),
]

urlpatterns = AuthorURLConf + BookURLConf + FriendURLConf

p_library/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    full_name = models.TextField()
    birth_year = models.SmallIntegerField()
    country = models.CharField(max_length=2)

    def __str__(self):
        return self.full_name


class Friend(models.Model):
    name = models.CharField('Имя друга', max_length=30, unique=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    ISBN = models.CharField(max_length=13)
    title = models.CharField(max_length=50, unique=True,)
    description = models.TextField()
    year_release = models.SmallIntegerField()
    copy_count = models.SmallIntegerField(default=1)
    price = models.DecimalField(default=None, max_digits=19, decimal_places=2)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, related_name='author_books')
    friend = models.ForeignKey(Friend, on_delete=models.SET_NULL,
                               related_name='friend_books', null=True, blank=True)
    photo = models.ImageField(upload_to='books/photo', blank=True)

    def __str__(self):
        return self.title

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>
            {% block title %} {% endblock title %} :: Библиотека
        </title>
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'main.css' %}" type="text/css" />
        <script src="https://kit.fontawesome.com/e3eb6d403a.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container mt-5">
            <header class="justify-content-center">
                <h1>Персональная библиотека</h1>
            </header>
            <div class="content pb-5">
                <div class="content__left-menu">
                    <aside>{% block left_menu %} {% endblock left_menu %}</aside>
                </div>
                <div class="content__main">
                    <main>{% block main %} {% endblock main %}</main>
                </div>
                <div class="content__messages">
                    {% if messages %}
                        <ul class="message-list text-info">
                            {% for message in messages %}
                                <li class="{{ message.tags }}">
                                    <b>{{ message}}</b>
                                    
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <footer>{% block footer %} {% endblock footer %}</footer>
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        
    </body>
</html>

templates/book_add.html
<!-- Наследуемся от базового шаблона -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- Титульник -->
{% block title %} Добавить книгу {% endblock title %} 

<!-- Подгружаем список авторов -->


{% block main %}

  <form action="" method="post" novalidate>
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-3 mb-0">
            {{ form.title|as_crispy_field }}
            
        </div>
        <div class="form-group col-3 mb-0">
            {{ form.author|as_crispy_field }}
        </div>
        <div class="form-group col-2 mb-0">
            {{ form.ISBN|as_crispy_field }}
        </div>

    </div>
    <div class="form-row">
        <div class="form-group col-2 mb-0">
            {{ form.year_release|as_crispy_field }}
            
        </div>
        <div class="form-group col-2 mb-0">
            {{ form.copy_count|as_crispy_field }}
        </div>
        <div class="form-group col-2 mb-0">
            {{ form.price|as_crispy_field }}
        </div>
        <div class="form-group col-3 mb-0 d-flex align-items-center">
            {{ form.friend|as_crispy_field }}
            <div class="addfriend__icons">
                <a href="{% url 'p_library:friend_add' author_id=author_by.id %}"><i class="fas fa-plus-circle"></i></a>
            </div> 
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-9 mb-0">
            {{ form.description|as_crispy_field }}
        </div>
    </div>  
    <a href="{% url 'p_library:books_list' author_id=author_by.id%}?page={{pn}}" class="btn btn-secondary mr-2" role="button" aria-pressed="true">Назад</a>  
    <button type="submit" class="btn btn-primary">Добавить книгу</button>
        
  </form>    
{% endblock main %}
    

templates/book_delete.html
<!-- Наследуемся от базового шаблона -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- Титульник -->
{% block title %} Редактировать книгу {% endblock title %} 

<!-- Подгружаем список авторов -->


{% block main %}
    <h1 class="text-danger text-center mb-4 mt-4" >Вы уверены ,что хотите удалить данную книгу?</h1>
    <h2>Описание книги</h2>
    <hr>
    <p class="book-description"><em>&nbsp;{{book.description|linebreaksbr}}</em></p>
    <hr>
    <h2>Подробная информация</h2>
    <h6>ISBN: <span class="detail-info text-success">{{book.ISBN}}</span></h6>
    <h6>Год релиза: <span class="detail-info text-info">{{book.year_release}}</span></h6>
    <h6>Число копий: <span class="detail-info text-info">{{book.copy_count}}</span></h6>
    <h6>Цена: <span class="detail-info text-info">{{book.price}}&#x20bd;</span></h6>
    <h6>Автор: <span class="detail-info text-info">{{book.author.full_name}}</span></h6>
    <div class="d-flex mt-4">
        <a href="{% url 'p_library:books_list' author_id=author_by.id%}?page={{pn}}" class="btn btn-secondary" role="button" aria-pressed="true">Назад</a>
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input class="btn btn-danger ml-2" type="submit" value="Удалить книгу">
        </form>
    </div>
    
{% endblock main %}

templates/book_detail.html
<!-- Наследуемся от базового шаблона -->
{% extends 'base.html' %}

<!-- Титульник -->
{% block title %} {{book.title}} {% endblock title %} 

{% block main %}
    <div class="book-detail">
        <h1 class="display-4 mb-3 mt-3">{{book.title}}</h1>
        {% if book.photo %} <img src="{{book.photo.url}}" class="img-thumbnail mt-2 mb-2" width="200" height="200"> {% endif %}
        <h2>Описание книги</h2>
        <hr>
        <p class="book-description"><em>&nbsp;{{book.description|linebreaksbr}}</em></p>
        <hr>
        <h2>Подробная информация</h2>
        <h6>ISBN: <span class="detail-info text-success">{{book.ISBN}}</span></h6>
        <h6>Год релиза: <span class="detail-info text-info">{{book.year_release}}</span></h6>
        <h6>Число копий: <span class="detail-info text-info">{{book.copy_count}}</span></h6>
        <h6>Цена: <span class="detail-info text-info">{{book.price}}&#x20bd;</span></h6>
        <h6>Автор: <span class="detail-info text-info">{{book.author.full_name}}</span></h6>
        <a href="{% url 'p_library:books_list' author_id=author_by.id%}?page={{pn}}" class="btn btn-secondary mt-4" role="button" aria-pressed="true">Назад</a>
    </div>
    
{% endblock main %}
    

templates/book_update.html
<!-- Наследуемся от базового шаблона -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- Титульник -->
{% block title %} Редактировать книгу {% endblock title %} 


{% block main %}


  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-3 mb-0">
            {{ form.title|as_crispy_field }}
        </div>
        <div class="form-group col-3 mb-0">
            {{ form.author|as_crispy_field }}
        </div>
        <div class="form-group col-2 mb-0">
            {{ form.ISBN|as_crispy_field }}
        </div>

    </div>
    <div class="form-row">
        <div class="form-group col-2 mb-0">
            {{ form.year_release|as_crispy_field }}
            
        </div>
        <div class="form-group col-2 mb-0">
            {{ form.copy_count|as_crispy_field }}
        </div>
        <div class="form-group col-2 mb-0">
            {{ form.price|as_crispy_field }}
        </div>
        <div id="addfriend" class="form-group d-flex align-items-center col-3 mb-0">
            {{ form.friend|as_crispy_field }}
            <div class="addfriend__icons">
                
                {% if book.friend.id %}
                <a href="{% url 'p_library:friend_edit' friend_id=book.friend.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                <a href="{% url 'p_library:friend_delete' friend_id=book.friend.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                {% endif %}  
            </div> 
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-9 mb-0">
            {{ form.description|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-3 mb-0">
            {{ form.photo|as_crispy_field }}
        </div>
    </div>
    
    <div class="d-flex  mt-4">
        <a href="{% url 'p_library:books_list' author_id=author_by.id%}?page={{pn}}" class="btn btn-secondary mr-2" role="button" aria-pressed="true">Назад</a>    
        <button type="submit" class="btn btn-primary">Изменить</button>
    </div>
  </form>    
{% endblock main %}
    

templates/books_list.html
<!-- Наследуемся от базового шаблона -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- Титульник -->
{% block title %} Список книг {% endblock title %} 

<!-- Подгружаем список авторов -->
{% block left_menu %} {% include 'includes/author_menu.html' %} {% endblock left_menu %}



{% block main %}
<!-- Список книг -->
<div class="books-list">
    <table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">&nbsp;</th>
            <th scope="col">Название</th>
            <th scope="col">Описание</th>
            <th scope="col">Цена</th>
            <th scope="col">Друг</th>
            <th scope="col">&nbsp;</th>
            <th scope="col">&nbsp;</th>
        </tr>
    </thead>
    <tbody class="bg-light">
        
        {% for book in book_list %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>
            {% if book.photo %} <img src="{{book.photo.url}}" class="img-thumbnail" width="100"> {% endif %}</td>
            <td><a class="text-info" href="{% url 'p_library:book_detail' book_id=book.id %}?page={{page_obj.number}}">{{book.title}}</a></td>
            <td>{{book.description}}</td>
            <td>{{book.price}}&#x20bd;</td>
            <td>{{book.friend}}</td>
            <td><a class="btn btn-outline-info" href="{% url 'p_library:book_update' book_id=book.id %}?page={{page_obj.number}}" role="button">Изменить</a></td>
            <td><a class="btn btn-danger" href="{% url 'p_library:book_delete' book_id=book.id %}?page={{page_obj.number}}" role="button">Удалить</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- кнопка добавления книги     -->
<a class="btn btn-sm btn-success" href="{% url 'p_library:book_add' author_id=author_by.id %}" role="button">Добавить книгу</a>

<!-- Постраничный вывод -->
<div class="pagination">
    <div class="step-links d-flex justify-content-around m-auto">
        <div class="previous">
            {% if page_obj.has_previous %}
            <!-- <a href="{% url 'p_library:books_list' author_id=author_by.id %}?page=1">&laquo; first</a> -->
            <a href="{% url 'p_library:books_list' author_id=author_by.id %}?page={{ page_obj.previous_page_number }}">
                <span class="badge badge-pill badge-info"><<</span>
            </a>    
            {% endif %}
        </div>
        

        <div class="current mr-5 ml-5">
            <b>Страница {{ page_obj.number }} из {{ paginator.num_pages }}.</b>   
        </div>
        
        <div class="next">
            {% if page_obj.has_next %}
            <a href="{% url 'p_library:books_list' author_id=author_by.id %}?page={{ page_obj.next_page_number }}">
                <span class="badge badge-pill badge-info">>></span>
            </a>
            <!-- <a href="{% url 'p_library:books_list' author_id=author_by.id %}?page={{ paginator.num_pages }}">last &raquo;</a> -->
            {% endif %}
        </div> 
    </div>
</div> 
{% endblock main %}

templates/friend_add.html
<!-- Наследуемся от базового шаблона -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- Титульник -->
{% block title %} Добавление друга {% endblock title %} 


{% block main %}
<form action="" method="post" novalidate>
    <div class="form-row">
        <div class="form-group col-3 mb-0">
            {{ form.name|as_crispy_field }} 
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Добавить друга</button>
  </form>    
{% endblock main %}

templates/friend_delete.html
<!-- Наследуемся от базового шаблона -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- Титульник -->
{% block title %} Добавление друга {% endblock title %} 


{% block main %}
<div class="friend-delete">
    <h2 >Имя друга:</b>
    <h1 class="display-4 ml-5 mb-3 mt-3"> {{friend.name}}</p>
</div>
<form action="" method="POST">
    {{form}}
    <input class="btn btn-danger mt-5" type="submit" value="Удалить друга">
</form>  
{% endblock main %}

templates/friend_edit.html
<!-- Наследуемся от базового шаблона -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- Титульник -->
{% block title %} Добавление друга {% endblock title %} 


{% block main %}
<form action="" method="post" novalidate>
    <div class="form-row">
        <div class="form-group col-3 mb-0">
            {{ form.name|as_crispy_field }} 
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Изменить</button>

  </form>

  
{% endblock main %}